spring.application.name=sistema

spring.datasource.url=jdbc:postgresql://localhost:5432/sistema_comercial
spring.datasource.username=postgres
spring.datasource.password=17012005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
